version: "3.8"

services:
  db:
    image: postgres:15
    container_name: microservice_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: clientes_db
    ports:
      - "5432:5432"

  app:
    build: ./app
    container_name: microservice_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin123
      DATABASE_NAME: clientes_db
    depends_on:
      - db
